version: '2'
services:
   db:
        image: postgres:12
        restart: always
        environment:
                - POSTGRES_USER=odoo
                - POSTGRES_PASSWORD=odoo
                - POSTGRES_DB=postgres
                - PGDATA=/var/lib/postgresql/data/pgdata
        ports:
                - 5151:5432
        volumes:
                - db-data:/var/lib/postgresql/data/pgdata
        networks:
                - odoo
   odoo:
        image: odoo:15.0
        restart: always
        ports:
                - 8116:8069
                - 2020:8072
        links:
                - db:db
        depends_on:
                - db
        volumes:
                - ./config:/etc/odoo
                - ./custom-addons:/mnt/custom-addons
                - odoo-data:/var/lib/odoo
        networks:
                - odoo
volumes:
        odoo-data:
        db-data:
networks:
        odoo: