# -*- coding: utf-8 -*-
{
    'name': "Ooh Logistic Apis",
    'version': "15.0",
    'author': "@The-Kadweka",
    'category': "Tools",
    'support': "DevzKona",
    'website': "husseinkadweka.com",
    'summary': "An Mpesa Intergration to allow payments",
    'description': """This is a module that holds and stores mpesa payments""",
    'license': 'LGPL-3',
    'depends': ['base', 'mail'],
    'data': [],
    'images': ['static/description/banner.jpg'],
    'application': True,
}
# ("asset_receivable", "Receivable"),
#             ("asset_cash", "Bank and Cash"),
#             ("asset_current", "Current Assets"),
#             ("asset_non_current", "Non-current Assets"),
#             ("asset_prepayments", "Prepayments"),
#             ("asset_fixed", "Fixed Assets"),
#             ("liability_payable", "Payable"),
#             ("liability_credit_card", "Credit Card"),
#             ("liability_current", "Current Liabilities"),
#             ("liability_non_current", "Non-current Liabilities"),
#             ("equity", "Equity"),
#             ("equity_unaffected", "Current Year Earnings"),
#             ("income", "Income"),
#             ("income_other", "Other Income"),
#             ("expense", "Expenses"),
#             ("expense_depreciation", "Depreciation"),
#             ("expense_direct_cost", "Cost of Revenue"),
#             ("off_balance", "Off-Balance Sheet"),
